package com.yuanqi.app.photo.service;
import com.yuanqi.app.common.api.ErrorCode;import com.yuanqi.app.common.api.PageResult;import com.yuanqi.app.common.exception.BusinessException;import com.yuanqi.app.common.text.UnicodeText;import com.yuanqi.app.photo.vo.MediaViews;import com.yuanqi.app.photo.vo.PublicPhotoViews;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
import java.sql.ResultSet;import java.sql.SQLException;import java.time.ZoneOffset;import java.util.*;
@Service public class PublicPhotoService{
 private final JdbcTemplate jdbc;public PublicPhotoService(JdbcTemplate j){jdbc=j;}
 @Transactional(readOnly=true) public PageResult<PublicPhotoViews.Card> feed(Long viewer,String keyword,String category,List<String>tagIds,int page){
  if(page<1)throw new BusinessException(ErrorCode.INVALID_PAGE);List<String> tags=tagIds==null?List.of():tagIds.stream().distinct().toList();if(tags.size()>5)throw new BusinessException(ErrorCode.INVALID_FILTER);
  List<String> terms=keyword==null?List.of():UnicodeText.searchTerms(keyword);if(terms.size()>5)throw new BusinessException(ErrorCode.INVALID_QUERY);
  StringBuilder from=new StringBuilder(" FROM photo_work w JOIN photo_revision r ON r.id=w.public_revision_id JOIN user_account a ON a.id=w.author_account_id JOIN user_profile p ON p.account_id=a.id LEFT JOIN photo_category c ON c.id=r.category_id WHERE w.publication_state='PUBLISHED'");List<Object> args=new ArrayList<>();
  if(category!=null){from.append(" AND c.public_id=?");args.add(category);}for(String tag:tags){from.append(" AND EXISTS(SELECT 1 FROM revision_tag rt JOIN photo_tag t ON t.id=rt.tag_id WHERE rt.revision_id=r.id AND t.tag_id=?)");args.add(tag);}for(String term:terms){from.append(" AND (r.title LIKE ? OR r.description LIKE ? OR r.location LIKE ? OR p.username LIKE ? OR EXISTS(SELECT 1 FROM revision_tag rt JOIN photo_tag t ON t.id=rt.tag_id WHERE rt.revision_id=r.id AND t.display_name LIKE ?))");String like="%"+term+"%";for(int i=0;i<5;i++)args.add(like);}
  long total=jdbc.queryForObject("SELECT COUNT(*)"+from,Long.class,args.toArray());String select="SELECT w.id internal_work_id,w.work_id,r.title,a.uid,p.username,c.public_id category_id,c.name category_name,c.active,w.published_at,"+
    "(SELECT m.media_id FROM revision_media rm JOIN media_asset m ON m.id=rm.media_id WHERE rm.revision_id=r.id ORDER BY rm.position LIMIT 1) cover_id,"+
    "(SELECT COUNT(*) FROM photo_like l WHERE l.work_id=w.id) likes,(SELECT COUNT(*) FROM photo_comment pc WHERE pc.work_id=w.id AND pc.display_state='ACTIVE') comments"+from+" ORDER BY w.published_at DESC,w.work_id DESC LIMIT 20 OFFSET ?";List<Object> queryArgs=new ArrayList<>(args);queryArgs.add((page-1)*20);
  List<PublicPhotoViews.Card> items=jdbc.query(select,(rs,n)->card(rs,viewer),queryArgs.toArray());return PageResult.of(items,page,20,total);
 }
 @Transactional(readOnly=true) public PublicPhotoViews.Detail detail(Long viewer,String workId){
  String sql="SELECT w.id internal_work_id,w.work_id,r.id internal_revision_id,r.revision_id,r.title,r.description,r.location,a.uid,p.username,c.public_id category_id,c.name category_name,c.active,w.published_at FROM photo_work w JOIN photo_revision r ON r.id=w.public_revision_id JOIN user_account a ON a.id=w.author_account_id JOIN user_profile p ON p.account_id=a.id LEFT JOIN photo_category c ON c.id=r.category_id WHERE w.work_id=? AND w.publication_state='PUBLISHED'";
  List<PublicPhotoViews.Detail> rows=jdbc.query(sql,(rs,n)->{long wid=rs.getLong("internal_work_id"),rid=rs.getLong("internal_revision_id");List<String>tags=jdbc.queryForList("SELECT t.display_name FROM revision_tag rt JOIN photo_tag t ON t.id=rt.tag_id WHERE rt.revision_id=? ORDER BY rt.position",String.class,rid);List<MediaViews.WebMedia>media=jdbc.query("SELECT m.media_id,m.mime_type,m.width,m.height,m.row_version FROM revision_media rm JOIN media_asset m ON m.id=rm.media_id WHERE rm.revision_id=? ORDER BY rm.position",(mr,i)->web(mr),rid);return new PublicPhotoViews.Detail(rs.getString("work_id"),rs.getString("revision_id"),rs.getString("title"),rs.getString("description"),rs.getString("location"),new PublicPhotoViews.Author(rs.getString("uid"),rs.getString("username")),category(rs),tags,media,rs.getTimestamp("published_at").toLocalDateTime().atOffset(ZoneOffset.UTC),count("photo_like",wid),jdbc.queryForObject("SELECT COUNT(*) FROM photo_comment WHERE work_id=? AND display_state='ACTIVE'",Long.class,wid),liked(viewer,wid));},workId);if(rows.isEmpty())throw new BusinessException(ErrorCode.RESOURCE_NOT_FOUND);return rows.get(0);
 }
 private PublicPhotoViews.Card card(ResultSet rs,Long viewer)throws SQLException{long wid=rs.getLong("internal_work_id");String cover=rs.getString("cover_id");MediaViews.WebMedia media=cover==null?null:new MediaViews.WebMedia(cover,"PUBLIC_URL","/api/v1/media/"+cover+"/web","image/jpeg",null,null,null);return new PublicPhotoViews.Card(rs.getString("work_id"),rs.getString("title"),media,new PublicPhotoViews.Author(rs.getString("uid"),rs.getString("username")),category(rs),rs.getTimestamp("published_at").toLocalDateTime().atOffset(ZoneOffset.UTC),rs.getLong("likes"),rs.getLong("comments"),liked(viewer,wid));}
 private PublicPhotoViews.Category category(ResultSet rs)throws SQLException{String id=rs.getString("category_id");return id==null?null:new PublicPhotoViews.Category(id,rs.getString("category_name"),rs.getBoolean("active"),true);}private MediaViews.WebMedia web(ResultSet r)throws SQLException{return new MediaViews.WebMedia(r.getString("media_id"),"PUBLIC_URL","/api/v1/media/"+r.getString("media_id")+"/web",r.getString("mime_type"),r.getInt("width"),r.getInt("height"),"\"media-"+r.getLong("row_version")+"\"");}
 private long count(String table,long id){return jdbc.queryForObject("SELECT COUNT(*) FROM "+table+" WHERE work_id=?",Long.class,id);}private Boolean liked(Long viewer,long wid){return viewer==null?null:Boolean.TRUE.equals(jdbc.queryForObject("SELECT COUNT(*)>0 FROM photo_like WHERE work_id=? AND account_id=?",Boolean.class,wid,viewer));}
}
