package com.yuanqi.app.photo.service;
import com.yuanqi.app.auth.entity.Account;import com.yuanqi.app.auth.mapper.AccountMapper;import com.yuanqi.app.common.api.ErrorCode;import com.yuanqi.app.common.exception.BusinessException;import com.yuanqi.app.photo.entity.PhotoWork;import com.yuanqi.app.photo.mapper.PhotoWorkMapper;import com.yuanqi.app.photo.vo.WorkViews;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
import java.time.Clock;import java.time.LocalDateTime;import java.time.ZoneOffset;import java.util.List;
@Service public class WorkDeletionService{private final PhotoWorkMapper works;private final AccountMapper accounts;private final JdbcTemplate jdbc;private final Clock clock;public WorkDeletionService(PhotoWorkMapper w,AccountMapper a,JdbcTemplate j,Clock c){works=w;accounts=a;jdbc=j;clock=c;}
 @Transactional public WorkViews.DeleteResult delete(Long actorId,String workId,String ifMatch,boolean confirmation){if(!confirmation)throw new BusinessException(ErrorCode.VALIDATION_FAILED);PhotoWork work=works.findByPublicIdForUpdate(workId);if(work==null||!actorId.equals(work.getAuthorAccountId()))throw new BusinessException(ErrorCode.RESOURCE_NOT_FOUND);match(ifMatch,work);Account author=accounts.selectById(work.getAuthorAccountId());Account actor=accounts.selectById(actorId);LocalDateTime now=now();
  List<Long>media=jdbc.queryForList("SELECT DISTINCT rm.media_id FROM photo_revision r JOIN revision_media rm ON rm.revision_id=r.id WHERE r.work_id=?",Long.class,work.getId());
  jdbc.update("INSERT INTO photo_tombstone(work_id,author_uid,deleted_by_uid,state_before_delete,deleted_at,last_moderation_action,last_reviewer_uid,last_reviewed_at,reason) SELECT ?,?,?,?,?,me.action,ra.uid,me.occurred_at,NULL FROM (SELECT 1) x LEFT JOIN moderation_event me ON me.id=(SELECT id FROM moderation_event WHERE work_id=? ORDER BY occurred_at DESC,id DESC LIMIT 1) LEFT JOIN user_account ra ON ra.id=me.reviewer_account_id",work.getWorkId(),author.getUid(),actor.getUid(),work.getPublicationState(),now,work.getId());
  work.setPublicRevisionId(null);work.setWorkingRevisionId(null);works.updateById(work);works.deleteById(work.getId());
  for(Long id:media)if(!Boolean.TRUE.equals(jdbc.queryForObject("SELECT COUNT(*)>0 FROM revision_media WHERE media_id=?",Boolean.class,id)))jdbc.update("INSERT IGNORE INTO media_cleanup_job(media_id,reason,status,attempt_count,next_attempt_at,deadline_at,created_at,updated_at) VALUES(?,?,'PENDING',0,?,?,?,?)",id,"WORK_DELETED",now,now.plusHours(24),now,now);
  return new WorkViews.DeleteResult(workId,true,now.atOffset(ZoneOffset.UTC));}
 private void match(String v,PhotoWork w){if(v==null)throw new BusinessException(ErrorCode.PRECONDITION_REQUIRED);if(!("\"work-"+w.getRowVersion()+"\"").equals(v))throw new BusinessException(ErrorCode.PRECONDITION_FAILED);}private LocalDateTime now(){return LocalDateTime.ofInstant(clock.instant(),ZoneOffset.UTC);}}
