package com.yuanqi.app.photo.service;
import com.yuanqi.app.common.http.StrongEtag;import com.yuanqi.app.photo.entity.MediaAsset;import com.yuanqi.app.photo.mapper.MediaAssetMapper;
import com.yuanqi.app.auth.entity.Account;import com.yuanqi.app.auth.mapper.AccountMapper;import com.yuanqi.app.common.api.ErrorCode;import com.yuanqi.app.common.exception.BusinessException;import com.yuanqi.app.photo.entity.PhotoWork;import com.yuanqi.app.photo.mapper.PhotoWorkMapper;import com.yuanqi.app.photo.vo.WorkViews;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
import java.time.Clock;import java.time.LocalDateTime;import java.time.ZoneOffset;import java.util.List;
@Service public class WorkDeletionService{private final PhotoWorkMapper works;private final AccountMapper accounts;private final JdbcTemplate jdbc;private final Clock clock;private final MediaAssetMapper mediaAssets;private final MediaCleanupService cleanup;public WorkDeletionService(PhotoWorkMapper w,AccountMapper a,JdbcTemplate j,Clock c,MediaAssetMapper m,MediaCleanupService cleanup){works=w;accounts=a;jdbc=j;clock=c;mediaAssets=m;this.cleanup=cleanup;}
 @Transactional public WorkViews.DeleteResult delete(Long actorId,String workId,String ifMatch,boolean confirmation){return perform(actorId,workId,ifMatch,confirmation,true,null);}
 @Transactional public WorkViews.DeleteResult deleteAdmin(Long actorId,String workId,String ifMatch,boolean confirmation,String reason){return perform(actorId,workId,ifMatch,confirmation,false,com.yuanqi.app.auth.support.AuthPolicy.validateReason(reason));}
 private WorkViews.DeleteResult perform(Long actorId,String workId,String ifMatch,boolean confirmation,boolean ownerOnly,String reason){if(!confirmation)throw new BusinessException(ErrorCode.VALIDATION_FAILED);PhotoWork work=works.findByPublicIdForUpdate(workId);if(work==null||(ownerOnly&&!actorId.equals(work.getAuthorAccountId())))throw new BusinessException(ErrorCode.RESOURCE_NOT_FOUND);match(ifMatch,work);Account author=accounts.selectById(work.getAuthorAccountId());Account actor=accounts.selectById(actorId);LocalDateTime now=now();
  List<Long>media=jdbc.queryForList("SELECT DISTINCT rm.media_id FROM photo_revision r JOIN revision_media rm ON rm.revision_id=r.id WHERE r.work_id=?",Long.class,work.getId());
  jdbc.update("INSERT INTO photo_tombstone(work_id,author_uid,deleted_by_uid,state_before_delete,deleted_at,last_moderation_action,last_reviewer_uid,last_reviewed_at,reason) SELECT ?,?,?,?,?,me.action,ra.uid,me.occurred_at,? FROM (SELECT 1) x LEFT JOIN moderation_event me ON me.id=(SELECT id FROM moderation_event WHERE work_id=? ORDER BY occurred_at DESC,id DESC LIMIT 1) LEFT JOIN user_account ra ON ra.id=me.reviewer_account_id",work.getWorkId(),author.getUid(),actor.getUid(),work.getPublicationState(),now,reason,work.getId());
  jdbc.update("UPDATE photo_work SET public_revision_id=NULL,working_revision_id=NULL WHERE id=?",work.getId());works.deleteById(work.getId());
  for(Long id:media)if(!mediaAssets.isReferenced(id)){MediaAsset asset=mediaAssets.selectById(id);cleanup.logicalDelete(asset,"WORK_DELETED");}
  return new WorkViews.DeleteResult(workId,true,now.atOffset(ZoneOffset.UTC));}
 private void match(String v,PhotoWork w){StrongEtag.requireMatch(v,"\"work-"+w.getRowVersion()+"\"");}private LocalDateTime now(){return LocalDateTime.ofInstant(clock.instant(),ZoneOffset.UTC);}}
