package com.yuanqi.app.user.controller;
import com.yuanqi.app.common.api.Result;import com.yuanqi.app.common.context.UserContext;import com.yuanqi.app.user.dto.GovernanceRequests;import com.yuanqi.app.user.service.GovernanceService;import com.yuanqi.app.user.vo.GovernanceViews;import io.swagger.v3.oas.annotations.Operation;import io.swagger.v3.oas.annotations.security.SecurityRequirement;import jakarta.validation.Valid;import org.springframework.http.HttpHeaders;import org.springframework.http.ResponseEntity;import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/api/v1/admin/users") @SecurityRequirement(name="Authorization") public class AdminUserController{
 private final GovernanceService service;public AdminUserController(GovernanceService s){service=s;}
 @Operation(summary="分页查询普通用户治理摘要") @GetMapping public Result<GovernanceViews.AccountPage> list(@RequestParam(required=false)String uid,@RequestParam(required=false)String governanceStatus,@RequestParam(defaultValue="1")int page,@RequestParam(defaultValue="20")int pageSize,@RequestParam(defaultValue="JOINED_AT_DESC")String sort,jakarta.servlet.http.HttpServletRequest http){java.util.Set<String> allowed=java.util.Set.of("uid","governanceStatus","page","pageSize","sort");for(var e:http.getParameterMap().entrySet())if(!allowed.contains(e.getKey())||e.getValue().length!=1)throw new com.yuanqi.app.common.exception.BusinessException(com.yuanqi.app.common.api.ErrorCode.INVALID_QUERY);return Result.success(service.list(uid,governanceStatus,page,pageSize,sort));}
 @Operation(summary="禁用普通用户并立即吊销全部 Session") @PostMapping("/{uid}/disable") public ResponseEntity<Result<GovernanceViews.AccountSummary>> disable(@PathVariable String uid,@RequestHeader(value=HttpHeaders.IF_MATCH,required=false)String match,@Valid @RequestBody GovernanceRequests.Reason r){return response(service.change(UserContext.getUserId(),uid,match,r.reason(),true));}
 @Operation(summary="解禁普通用户；不恢复旧 Session") @PostMapping("/{uid}/enable") public ResponseEntity<Result<GovernanceViews.AccountSummary>> enable(@PathVariable String uid,@RequestHeader(value=HttpHeaders.IF_MATCH,required=false)String match,@Valid @RequestBody GovernanceRequests.Reason r){return response(service.change(UserContext.getUserId(),uid,match,r.reason(),false));}
 private ResponseEntity<Result<GovernanceViews.AccountSummary>> response(GovernanceViews.AccountSummary v){return ResponseEntity.ok().header(HttpHeaders.ETAG,v.versionTag()).body(Result.success(v));}
}
