spring.application.name=app


spring.datasource.url=jdbc:mysql://localhost:3306/blog?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
spring.datasource.username=root
# 这里请替换为您本地 MySQL 真实的密码
spring.datasource.password=19970810
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# 设定单个文件上传的最大限制为 50MB
spring.servlet.multipart.max-file-size=50MB

# 设定单次请求中所有文件加起来的总限制为 100MB
spring.servlet.multipart.max-request-size=100MB

#执行sql的时候在控制台打印sql语句，用于debug
#mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl