package com.yuanqi.app.user.service;
import com.yuanqi.app.auth.support.PublicIdGenerator;import com.yuanqi.app.common.api.ErrorCode;import com.yuanqi.app.common.exception.BusinessException;import com.yuanqi.app.photo.entity.MediaAsset;import com.yuanqi.app.photo.mapper.MediaAssetMapper;import com.yuanqi.app.photo.service.StoragePort;import com.yuanqi.app.photo.service.MediaCleanupService;import com.yuanqi.app.photo.vo.MediaViews;import com.yuanqi.app.user.entity.UserProfile;import com.yuanqi.app.user.mapper.UserProfileMapper;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import org.springframework.web.multipart.MultipartFile;import com.yuanqi.app.common.http.StrongEtag;
import javax.imageio.*;import javax.imageio.stream.ImageInputStream;import java.awt.*;import java.awt.image.BufferedImage;import java.io.*;import java.time.*;import java.util.*;
@Service public class AvatarService{private final UserProfileMapper profiles;private final MediaAssetMapper media;private final StoragePort storage;private final PublicIdGenerator ids;private final Clock clock;private final org.springframework.transaction.support.TransactionTemplate transactions;private final MediaCleanupService cleanup;public AvatarService(UserProfileMapper p,MediaAssetMapper m,StoragePort s,PublicIdGenerator i,Clock c,org.springframework.transaction.PlatformTransactionManager tm,MediaCleanupService cleanup){profiles=p;media=m;storage=s;ids=i;clock=c;transactions=new org.springframework.transaction.support.TransactionTemplate(tm);this.cleanup=cleanup;}
 public Mutation upload(Long accountId,String ifMatch,MultipartFile file){if(file==null||file.isEmpty())throw new BusinessException(ErrorCode.INVALID_CONTENT);if(file.getSize()>10L*1024*1024)throw new BusinessException(ErrorCode.FILE_TOO_LARGE);String id=ids.next(),key="avatar/"+id+".jpg";try{BufferedImage src=decode(file);int side=Math.min(src.getWidth(),src.getHeight()),x=(src.getWidth()-side)/2,y=(src.getHeight()-side)/2;BufferedImage out=new BufferedImage(512,512,BufferedImage.TYPE_INT_RGB);Graphics2D g=out.createGraphics();g.setColor(Color.WHITE);g.fillRect(0,0,512,512);g.setRenderingHint(RenderingHints.KEY_INTERPOLATION,RenderingHints.VALUE_INTERPOLATION_BICUBIC);g.drawImage(src,0,0,512,512,x,y,x+side,y+side,null);g.dispose();try(var output=storage.create(key)){ImageIO.write(out,"jpeg",output);}Mutation result=transactions.execute(s->save(accountId,ifMatch,id,key));if(result==null)throw new BusinessException(ErrorCode.INTERNAL_ERROR);return result;}catch(BusinessException e){compensate(key);throw e;}catch(Exception e){compensate(key);throw new BusinessException(ErrorCode.INVALID_CONTENT);}}
 private Mutation save(Long accountId,String ifMatch,String id,String key){UserProfile p=profiles.findForUpdate(accountId);match(ifMatch,p);LocalDateTime now=now();MediaAsset a=new MediaAsset();a.setMediaId(id);a.setClientUploadId(UUID.randomUUID().toString());a.setOwnerAccountId(accountId);a.setPurpose("AVATAR");a.setWebStorageKey(key);a.setMimeType("image/jpeg");a.setWidth(512);a.setHeight(512);a.setFrameCount(1);a.setStatus("READY");a.setRetryable(false);a.setRowVersion(0L);a.setCreatedAt(now);a.setUpdatedAt(now);media.insert(a);Long old=p.getAvatarMediaId();p.setAvatarMediaId(a.getId());p.setRowVersion(p.getRowVersion()+1);p.setUpdatedAt(now);profiles.updateById(p);if(old!=null)queue(old,now);return mutation(a,p);}
 @Transactional public Mutation delete(Long accountId,String ifMatch){UserProfile p=profiles.findForUpdate(accountId);match(ifMatch,p);Long old=p.getAvatarMediaId();p.setAvatarMediaId(null);p.setRowVersion(p.getRowVersion()+1);p.setUpdatedAt(now());profiles.updateById(p);if(old!=null)queue(old,now());return new Mutation(null,tag(p));}
 private void queue(Long id,LocalDateTime now){MediaAsset a=media.selectById(id);if(a!=null)cleanup.logicalDelete(a,"AVATAR_REPLACED");}
 private void compensate(String key){try{storage.delete(key);}catch(Exception failure){cleanup.enqueueStorage(key,"AVATAR_UPLOAD_COMPENSATION",now());}}
 private BufferedImage decode(MultipartFile f)throws Exception{try(ImageInputStream in=ImageIO.createImageInputStream(f.getInputStream())){var it=ImageIO.getImageReaders(in);if(!it.hasNext())throw new BusinessException(ErrorCode.UNSUPPORTED_FORMAT);ImageReader r=it.next();try{r.setInput(in,true,false);String n=r.getFormatName().toLowerCase(Locale.ROOT);if(!(n.contains("jpeg")||n.equals("png")||n.equals("webp")))throw new BusinessException(ErrorCode.UNSUPPORTED_FORMAT);if(r.getNumImages(true)!=1)throw new BusinessException(ErrorCode.DYNAMIC_IMAGE);return r.read(0);}finally{r.dispose();}}}
 private Mutation mutation(MediaAsset a,UserProfile p){return new Mutation(new MediaViews.WebMedia(a.getMediaId(),"PUBLIC_URL","/api/v1/media/"+a.getMediaId()+"/web",a.getMimeType(),512,512,"\"media-0\""),tag(p));}private void match(String v,UserProfile p){StrongEtag.requireMatch(v,tag(p));}private String tag(UserProfile p){return "\"profile-"+p.getRowVersion()+"\"";}private LocalDateTime now(){return LocalDateTime.ofInstant(clock.instant(),ZoneOffset.UTC);}public record Mutation(MediaViews.WebMedia avatar,String profileVersionTag){}
}
